controller_list:
  - name: fake_arm_robot_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
initial:  # Define initial robot poses.
  - group: arm_robot
    pose: home